/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReportRouteImport } from './routes/report'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as CitizenChallengesRouteImport } from './routes/citizen.challenges'
import { Route as CitizenDashboardRouteImport } from './routes/citizen.dashboard'
import { Route as CitizenSubmitRouteImport } from './routes/citizen.submit'
import { Route as DashboardRoleRouteImport } from './routes/dashboard.$role'
import { Route as DashboardGovRouteImport } from './routes/dashboard.gov'
import { Route as GovBidsRouteImport } from './routes/gov.bids'
import { Route as GovDashboardRouteImport } from './routes/gov.dashboard'
import { Route as GovEmergencyRouteImport } from './routes/gov.emergency'
import { Route as GovEvaluationRouteImport } from './routes/gov.evaluation'
import { Route as GovReviewRouteImport } from './routes/gov.review'
import { Route as GovernmentDashboardRouteImport } from './routes/government.dashboard'
import { Route as IndustryBidsRouteImport } from './routes/industry.bids'
import { Route as IndustryDashboardRouteImport } from './routes/industry.dashboard'
import { Route as IndustryOpenProjectsRouteImport } from './routes/industry.open-projects'
import { Route as UniversityAvailableRouteImport } from './routes/university.available'
import { Route as UniversityDashboardRouteImport } from './routes/university.dashboard'
import { Route as UniversityHistoryRouteImport } from './routes/university.history'
import { Route as UniversityProjectsRouteImport } from './routes/university.projects'
import { Route as UniversityProposalsRouteImport } from './routes/university.proposals'
import { Route as GovChallengeIdRouteImport } from './routes/gov.challenge.$id'
import { Route as GovVerificationIdRouteImport } from './routes/gov.verification.$id'
import { Route as IndustryProposalIdRouteImport } from './routes/industry.proposal.$id'
import { Route as UniversityChallengeIdRouteImport } from './routes/university.challenge.$id'
import { Route as UniversityProposalIdRouteImport } from './routes/university.proposal.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenChallengesRoute = CitizenChallengesRouteImport.update({
  id: '/citizen/challenges',
  path: '/citizen/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenDashboardRoute = CitizenDashboardRouteImport.update({
  id: '/citizen/dashboard',
  path: '/citizen/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenSubmitRoute = CitizenSubmitRouteImport.update({
  id: '/citizen/submit',
  path: '/citizen/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoleRoute = DashboardRoleRouteImport.update({
  id: '/dashboard/$role',
  path: '/dashboard/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGovRoute = DashboardGovRouteImport.update({
  id: '/dashboard/gov',
  path: '/dashboard/gov',
  getParentRoute: () => rootRouteImport,
} as any)
const GovBidsRoute = GovBidsRouteImport.update({
  id: '/gov/bids',
  path: '/gov/bids',
  getParentRoute: () => rootRouteImport,
} as any)
const GovDashboardRoute = GovDashboardRouteImport.update({
  id: '/gov/dashboard',
  path: '/gov/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GovEmergencyRoute = GovEmergencyRouteImport.update({
  id: '/gov/emergency',
  path: '/gov/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const GovEvaluationRoute = GovEvaluationRouteImport.update({
  id: '/gov/evaluation',
  path: '/gov/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const GovReviewRoute = GovReviewRouteImport.update({
  id: '/gov/review',
  path: '/gov/review',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentDashboardRoute = GovernmentDashboardRouteImport.update({
  id: '/government/dashboard',
  path: '/government/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryBidsRoute = IndustryBidsRouteImport.update({
  id: '/industry/bids',
  path: '/industry/bids',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryDashboardRoute = IndustryDashboardRouteImport.update({
  id: '/industry/dashboard',
  path: '/industry/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryOpenProjectsRoute = IndustryOpenProjectsRouteImport.update({
  id: '/industry/open-projects',
  path: '/industry/open-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityAvailableRoute = UniversityAvailableRouteImport.update({
  id: '/university/available',
  path: '/university/available',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityDashboardRoute = UniversityDashboardRouteImport.update({
  id: '/university/dashboard',
  path: '/university/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityHistoryRoute = UniversityHistoryRouteImport.update({
  id: '/university/history',
  path: '/university/history',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityProjectsRoute = UniversityProjectsRouteImport.update({
  id: '/university/projects',
  path: '/university/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityProposalsRoute = UniversityProposalsRouteImport.update({
  id: '/university/proposals',
  path: '/university/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const GovChallengeIdRoute = GovChallengeIdRouteImport.update({
  id: '/gov/challenge/$id',
  path: '/gov/challenge/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GovVerificationIdRoute = GovVerificationIdRouteImport.update({
  id: '/gov/verification/$id',
  path: '/gov/verification/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryProposalIdRoute = IndustryProposalIdRouteImport.update({
  id: '/industry/proposal/$id',
  path: '/industry/proposal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityChallengeIdRoute = UniversityChallengeIdRouteImport.update({
  id: '/university/challenge/$id',
  path: '/university/challenge/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityProposalIdRoute = UniversityProposalIdRouteImport.update({
  id: '/university/proposal/$id',
  path: '/university/proposal/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/citizen/challenges': typeof CitizenChallengesRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/citizen/submit': typeof CitizenSubmitRoute
  '/dashboard/$role': typeof DashboardRoleRoute
  '/dashboard/gov': typeof DashboardGovRoute
  '/gov/bids': typeof GovBidsRoute
  '/gov/dashboard': typeof GovDashboardRoute
  '/gov/emergency': typeof GovEmergencyRoute
  '/gov/evaluation': typeof GovEvaluationRoute
  '/gov/review': typeof GovReviewRoute
  '/government/dashboard': typeof GovernmentDashboardRoute
  '/industry/bids': typeof IndustryBidsRoute
  '/industry/dashboard': typeof IndustryDashboardRoute
  '/industry/open-projects': typeof IndustryOpenProjectsRoute
  '/university/available': typeof UniversityAvailableRoute
  '/university/dashboard': typeof UniversityDashboardRoute
  '/university/history': typeof UniversityHistoryRoute
  '/university/projects': typeof UniversityProjectsRoute
  '/university/proposals': typeof UniversityProposalsRoute
  '/gov/challenge/$id': typeof GovChallengeIdRoute
  '/gov/verification/$id': typeof GovVerificationIdRoute
  '/industry/proposal/$id': typeof IndustryProposalIdRoute
  '/university/challenge/$id': typeof UniversityChallengeIdRoute
  '/university/proposal/$id': typeof UniversityProposalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/citizen/challenges': typeof CitizenChallengesRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/citizen/submit': typeof CitizenSubmitRoute
  '/dashboard/$role': typeof DashboardRoleRoute
  '/dashboard/gov': typeof DashboardGovRoute
  '/gov/bids': typeof GovBidsRoute
  '/gov/dashboard': typeof GovDashboardRoute
  '/gov/emergency': typeof GovEmergencyRoute
  '/gov/evaluation': typeof GovEvaluationRoute
  '/gov/review': typeof GovReviewRoute
  '/government/dashboard': typeof GovernmentDashboardRoute
  '/industry/bids': typeof IndustryBidsRoute
  '/industry/dashboard': typeof IndustryDashboardRoute
  '/industry/open-projects': typeof IndustryOpenProjectsRoute
  '/university/available': typeof UniversityAvailableRoute
  '/university/dashboard': typeof UniversityDashboardRoute
  '/university/history': typeof UniversityHistoryRoute
  '/university/projects': typeof UniversityProjectsRoute
  '/university/proposals': typeof UniversityProposalsRoute
  '/gov/challenge/$id': typeof GovChallengeIdRoute
  '/gov/verification/$id': typeof GovVerificationIdRoute
  '/industry/proposal/$id': typeof IndustryProposalIdRoute
  '/university/challenge/$id': typeof UniversityChallengeIdRoute
  '/university/proposal/$id': typeof UniversityProposalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/citizen/challenges': typeof CitizenChallengesRoute
  '/citizen/dashboard': typeof CitizenDashboardRoute
  '/citizen/submit': typeof CitizenSubmitRoute
  '/dashboard/$role': typeof DashboardRoleRoute
  '/dashboard/gov': typeof DashboardGovRoute
  '/gov/bids': typeof GovBidsRoute
  '/gov/dashboard': typeof GovDashboardRoute
  '/gov/emergency': typeof GovEmergencyRoute
  '/gov/evaluation': typeof GovEvaluationRoute
  '/gov/review': typeof GovReviewRoute
  '/government/dashboard': typeof GovernmentDashboardRoute
  '/industry/bids': typeof IndustryBidsRoute
  '/industry/dashboard': typeof IndustryDashboardRoute
  '/industry/open-projects': typeof IndustryOpenProjectsRoute
  '/university/available': typeof UniversityAvailableRoute
  '/university/dashboard': typeof UniversityDashboardRoute
  '/university/history': typeof UniversityHistoryRoute
  '/university/projects': typeof UniversityProjectsRoute
  '/university/proposals': typeof UniversityProposalsRoute
  '/gov/challenge/$id': typeof GovChallengeIdRoute
  '/gov/verification/$id': typeof GovVerificationIdRoute
  '/industry/proposal/$id': typeof IndustryProposalIdRoute
  '/university/challenge/$id': typeof UniversityChallengeIdRoute
  '/university/proposal/$id': typeof UniversityProposalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/report'
    | '/admin/dashboard'
    | '/citizen/challenges'
    | '/citizen/dashboard'
    | '/citizen/submit'
    | '/dashboard/$role'
    | '/dashboard/gov'
    | '/gov/bids'
    | '/gov/dashboard'
    | '/gov/emergency'
    | '/gov/evaluation'
    | '/gov/review'
    | '/government/dashboard'
    | '/industry/bids'
    | '/industry/dashboard'
    | '/industry/open-projects'
    | '/university/available'
    | '/university/dashboard'
    | '/university/history'
    | '/university/projects'
    | '/university/proposals'
    | '/gov/challenge/$id'
    | '/gov/verification/$id'
    | '/industry/proposal/$id'
    | '/university/challenge/$id'
    | '/university/proposal/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/report'
    | '/admin/dashboard'
    | '/citizen/challenges'
    | '/citizen/dashboard'
    | '/citizen/submit'
    | '/dashboard/$role'
    | '/dashboard/gov'
    | '/gov/bids'
    | '/gov/dashboard'
    | '/gov/emergency'
    | '/gov/evaluation'
    | '/gov/review'
    | '/government/dashboard'
    | '/industry/bids'
    | '/industry/dashboard'
    | '/industry/open-projects'
    | '/university/available'
    | '/university/dashboard'
    | '/university/history'
    | '/university/projects'
    | '/university/proposals'
    | '/gov/challenge/$id'
    | '/gov/verification/$id'
    | '/industry/proposal/$id'
    | '/university/challenge/$id'
    | '/university/proposal/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/report'
    | '/admin/dashboard'
    | '/citizen/challenges'
    | '/citizen/dashboard'
    | '/citizen/submit'
    | '/dashboard/$role'
    | '/dashboard/gov'
    | '/gov/bids'
    | '/gov/dashboard'
    | '/gov/emergency'
    | '/gov/evaluation'
    | '/gov/review'
    | '/government/dashboard'
    | '/industry/bids'
    | '/industry/dashboard'
    | '/industry/open-projects'
    | '/university/available'
    | '/university/dashboard'
    | '/university/history'
    | '/university/projects'
    | '/university/proposals'
    | '/gov/challenge/$id'
    | '/gov/verification/$id'
    | '/industry/proposal/$id'
    | '/university/challenge/$id'
    | '/university/proposal/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ReportRoute: typeof ReportRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  CitizenChallengesRoute: typeof CitizenChallengesRoute
  CitizenDashboardRoute: typeof CitizenDashboardRoute
  CitizenSubmitRoute: typeof CitizenSubmitRoute
  DashboardRoleRoute: typeof DashboardRoleRoute
  DashboardGovRoute: typeof DashboardGovRoute
  GovBidsRoute: typeof GovBidsRoute
  GovDashboardRoute: typeof GovDashboardRoute
  GovEmergencyRoute: typeof GovEmergencyRoute
  GovEvaluationRoute: typeof GovEvaluationRoute
  GovReviewRoute: typeof GovReviewRoute
  GovernmentDashboardRoute: typeof GovernmentDashboardRoute
  IndustryBidsRoute: typeof IndustryBidsRoute
  IndustryDashboardRoute: typeof IndustryDashboardRoute
  IndustryOpenProjectsRoute: typeof IndustryOpenProjectsRoute
  UniversityAvailableRoute: typeof UniversityAvailableRoute
  UniversityDashboardRoute: typeof UniversityDashboardRoute
  UniversityHistoryRoute: typeof UniversityHistoryRoute
  UniversityProjectsRoute: typeof UniversityProjectsRoute
  UniversityProposalsRoute: typeof UniversityProposalsRoute
  GovChallengeIdRoute: typeof GovChallengeIdRoute
  GovVerificationIdRoute: typeof GovVerificationIdRoute
  IndustryProposalIdRoute: typeof IndustryProposalIdRoute
  UniversityChallengeIdRoute: typeof UniversityChallengeIdRoute
  UniversityProposalIdRoute: typeof UniversityProposalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/challenges': {
      id: '/citizen/challenges'
      path: '/citizen/challenges'
      fullPath: '/citizen/challenges'
      preLoaderRoute: typeof CitizenChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/dashboard': {
      id: '/citizen/dashboard'
      path: '/citizen/dashboard'
      fullPath: '/citizen/dashboard'
      preLoaderRoute: typeof CitizenDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/submit': {
      id: '/citizen/submit'
      path: '/citizen/submit'
      fullPath: '/citizen/submit'
      preLoaderRoute: typeof CitizenSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$role': {
      id: '/dashboard/$role'
      path: '/dashboard/$role'
      fullPath: '/dashboard/$role'
      preLoaderRoute: typeof DashboardRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/gov': {
      id: '/dashboard/gov'
      path: '/dashboard/gov'
      fullPath: '/dashboard/gov'
      preLoaderRoute: typeof DashboardGovRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gov/bids': {
      id: '/gov/bids'
      path: '/gov/bids'
      fullPath: '/gov/bids'
      preLoaderRoute: typeof GovBidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gov/dashboard': {
      id: '/gov/dashboard'
      path: '/gov/dashboard'
      fullPath: '/gov/dashboard'
      preLoaderRoute: typeof GovDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gov/emergency': {
      id: '/gov/emergency'
      path: '/gov/emergency'
      fullPath: '/gov/emergency'
      preLoaderRoute: typeof GovEmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gov/evaluation': {
      id: '/gov/evaluation'
      path: '/gov/evaluation'
      fullPath: '/gov/evaluation'
      preLoaderRoute: typeof GovEvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gov/review': {
      id: '/gov/review'
      path: '/gov/review'
      fullPath: '/gov/review'
      preLoaderRoute: typeof GovReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government/dashboard': {
      id: '/government/dashboard'
      path: '/government/dashboard'
      fullPath: '/government/dashboard'
      preLoaderRoute: typeof GovernmentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/bids': {
      id: '/industry/bids'
      path: '/industry/bids'
      fullPath: '/industry/bids'
      preLoaderRoute: typeof IndustryBidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/dashboard': {
      id: '/industry/dashboard'
      path: '/industry/dashboard'
      fullPath: '/industry/dashboard'
      preLoaderRoute: typeof IndustryDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/open-projects': {
      id: '/industry/open-projects'
      path: '/industry/open-projects'
      fullPath: '/industry/open-projects'
      preLoaderRoute: typeof IndustryOpenProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university/available': {
      id: '/university/available'
      path: '/university/available'
      fullPath: '/university/available'
      preLoaderRoute: typeof UniversityAvailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university/dashboard': {
      id: '/university/dashboard'
      path: '/university/dashboard'
      fullPath: '/university/dashboard'
      preLoaderRoute: typeof UniversityDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university/history': {
      id: '/university/history'
      path: '/university/history'
      fullPath: '/university/history'
      preLoaderRoute: typeof UniversityHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university/projects': {
      id: '/university/projects'
      path: '/university/projects'
      fullPath: '/university/projects'
      preLoaderRoute: typeof UniversityProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university/proposals': {
      id: '/university/proposals'
      path: '/university/proposals'
      fullPath: '/university/proposals'
      preLoaderRoute: typeof UniversityProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gov/challenge/$id': {
      id: '/gov/challenge/$id'
      path: '/gov/challenge/$id'
      fullPath: '/gov/challenge/$id'
      preLoaderRoute: typeof GovChallengeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gov/verification/$id': {
      id: '/gov/verification/$id'
      path: '/gov/verification/$id'
      fullPath: '/gov/verification/$id'
      preLoaderRoute: typeof GovVerificationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/proposal/$id': {
      id: '/industry/proposal/$id'
      path: '/industry/proposal/$id'
      fullPath: '/industry/proposal/$id'
      preLoaderRoute: typeof IndustryProposalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university/challenge/$id': {
      id: '/university/challenge/$id'
      path: '/university/challenge/$id'
      fullPath: '/university/challenge/$id'
      preLoaderRoute: typeof UniversityChallengeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university/proposal/$id': {
      id: '/university/proposal/$id'
      path: '/university/proposal/$id'
      fullPath: '/university/proposal/$id'
      preLoaderRoute: typeof UniversityProposalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ReportRoute: ReportRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  CitizenChallengesRoute: CitizenChallengesRoute,
  CitizenDashboardRoute: CitizenDashboardRoute,
  CitizenSubmitRoute: CitizenSubmitRoute,
  DashboardRoleRoute: DashboardRoleRoute,
  DashboardGovRoute: DashboardGovRoute,
  GovBidsRoute: GovBidsRoute,
  GovDashboardRoute: GovDashboardRoute,
  GovEmergencyRoute: GovEmergencyRoute,
  GovEvaluationRoute: GovEvaluationRoute,
  GovReviewRoute: GovReviewRoute,
  GovernmentDashboardRoute: GovernmentDashboardRoute,
  IndustryBidsRoute: IndustryBidsRoute,
  IndustryDashboardRoute: IndustryDashboardRoute,
  IndustryOpenProjectsRoute: IndustryOpenProjectsRoute,
  UniversityAvailableRoute: UniversityAvailableRoute,
  UniversityDashboardRoute: UniversityDashboardRoute,
  UniversityHistoryRoute: UniversityHistoryRoute,
  UniversityProjectsRoute: UniversityProjectsRoute,
  UniversityProposalsRoute: UniversityProposalsRoute,
  GovChallengeIdRoute: GovChallengeIdRoute,
  GovVerificationIdRoute: GovVerificationIdRoute,
  IndustryProposalIdRoute: IndustryProposalIdRoute,
  UniversityChallengeIdRoute: UniversityChallengeIdRoute,
  UniversityProposalIdRoute: UniversityProposalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
